### ISSUE TITLE
Preliminary results

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectA#2]
Dear Project A members,
I remind all of you that the deadline is coming Monday, Feb 29th.

All people (group 2 and group 3) have now been added to this repository. We expect contributions from everyone (up to now there have been contributions only from @theocheslerean and @Adiolis )

Also use github issues for every issues related to the code and project, as every contributor (thus both groups) will be able to visualize these and will be notified via email.

Cheers, Chris

**Comment by kordianbruck** [comment]
@sacdallago "preliminary results for review" - this means we can also keep working the week after right?

**Comment by sacdallago** [comment]
@kordianbruck correct. But the DB strutture should be very well defined, possibly some example data populate it and the extraction from the wiki should also be in a good state as other teams will start working on that data. If, then, you still need to define the api better and adjust the extraction of data, you have one week.

**Comment by kordianbruck** [comment]
So till monday the following issues must be done:
- [x] DB strutture should be very well defined #4 
- [x] some example data #12
- [x] extraction from the wiki #5

**Comment by sacdallago** [comment]
:+1:

**Comment by sacdallago** [comment]
@Rostlab/js_cs_sose_2016_students 

Team members of **Project A**: Please report here your intermediate results Today.
That is:
- [ ] How to access the data that you already downloaded? (retrieve data)
- [ ] Explain how other teams can use your DB,
- [ ] How it is structured,
- [ ] How you can generate data (from the wiki to the database),
- [ ] Anything else?

**Everyone else**: Please ask your questions regarding the APIs and the structure of the database for Project A here. Ah, and 

# [:point_right::star:**start coding**:star::point_left:](https://rostlab.org/~gyachdav/js16/html/)

**Comment by gyachdav** [comment]
Did you hear back? We didn't get anything from them.

**Comment by ghost** [comment]
Left a message on google groups about this issue, let's see if that has any effect.

**Comment by ghost** [comment]
It seems that no one besides me is actually working on these preliminary tasks (API, DB, Controller, Stores) and they are a bit too much for me alone in this short period of time, where i also got a tooth replaced (yesterday ;) ). I know, Boris and Theo are working on the scrapper stuff, but i could really need help to get this basic stuff done.

**Comment by gyachdav** [comment]
Note that even if you are not done with the API, it is still important that you provide other projects with the datasets that you already managed to get up till now. So this is not just your effort Michael but should be the entire group that is working on the scraper and the models.

**Comment by ghost** [comment]
Actually i described already some api calls in the wiki of this repo. 
https://github.com/Rostlab/JS16_ProjectA#services

Is that sufficient? After the models are final/fixed (i am actually reviewing them), i will add a description of them.

**Comment by gyachdav** [comment]
Others projects need to be able to start pulling data from your database. Is there such database that can be accessed by other groups? 

If not and you did not get around to making the database publicly accessible then we would like you to at least publish the structured datasets you managed to get off the wiki.   

Let us know if that is clear.

**Comment by kordianbruck** [comment]
@gyachdav do we have a server we can set this up on? currently everyone is using a local installation...

**Comment by ghost** [comment]
I already set up a mongoDB on mongoLab. We passed around the credentials on a more secure way.  I actually don´t know how we will manage this with the others groups.

**Comment by kordianbruck** [comment]
@Adiolis great to know - why was this not mentioned anywhere on Github or G-Groups?

**Comment by ghost** [comment]
It has been mentioned several times. We also have been stuck on this issue unless Christian helped us out. He provided the working code for this. Probably you missed that since the other group was formed pretty late.

**Comment by kordianbruck** [comment]
@Adiolis please point me to the posts, that contain the credentials or information for accessing the api - thanks!

**Comment by gyachdav** [comment]
Ideally you should've found a hosting solution and serve the results from there. As I mentioned in my previous note if such a solution does not exist, then just publish the datasets (you can just put them into a dedicated branch on your github repo). 

We can provide a server for you to host the db but that will take a bit of time. We need to know what the specifications for such a box will be (e.g. I tried installing your code onto a debian 7 and saw that none of the NPM pre-reqs are available so i wasn't sure how to proceed). keep in mind that all of this should have been discussed with us earlier...

**Comment by sacdallago** [comment]
@kordianbruck stay sassy ;) no need to get upset @Adiolis I am aware of mongoLab and I am aware of how to find things in your code, but other groups are invited to come here (this issue) to find all relevant information. You should maybe point out who to ask for the mongolab credentials, put a link to the db schema that @togiberlin posted, put the link (although obvious) to where the api information can be found and how to run the server locally (Many groups will need to do this, as you haven't hosted it. Mind: not bad! But, just make it clear to the other groups, you know ;) )... Yes.. You can also copy-paste text from other... say.. Readme.md's? :dancer:

**Comment by ghost** [comment]
This all has been discussed with Christian, who has helped us with this issue a lot since we have been unable to connect to the db for about 2 days. He fixed that. The database is working and online, but not filled with data yet, since the scrapper is not linked with the stores and the models are not fixed yet (theo and i are working on that today). Thus, some of us are still working locally with another configuration file since it makes really no difference by now and therefore it has not been remarkable if someone knows the mongoLab DB or not. 

The miscommunication with some parts of the other group is probably there, because this has been done before the other group has connected to us. It has been discussed on the google group, facebook and passed around to the people, that were interested in it.
Of course, a wiki site about connecting to the db is appropriate, but i am working already to my capacity and the actual state of the project makes no difference to a local or the global db. Hopefully, until tonight ;)

PS: I would appreciate help on the API, Stores, Controllers, Models.

**Comment by theocheslerean** [comment]
The scraper works for the houses, characters and episodes. It returns an array with only the names of them. Still have to work out how to get the rest of the information, say for example for a character.

**Comment by ghost** [comment]
Can be closed?
The fillers now populate the db. (not with all details, but still to come ;) )

**Comment by sacdallago** [comment]
Unbelievable: I thought I would never see this issue closed :stuck_out_tongue_closed_eyes: :stuck_out_tongue_closed_eyes: :stuck_out_tongue_closed_eyes: :stuck_out_tongue_closed_eyes: :stuck_out_tongue_closed_eyes: :stuck_out_tongue_closed_eyes: :stuck_out_tongue_closed_eyes: 
Nice job!

**Comment by gyachdav** [comment]
Really? I still get dummy data for https://got-api.bruck.me/api/characters/

**Comment by ghost** [comment]
Well, @kordianbruck needs to perform the filler methods on his server.
We all have no access to it.

**Comment by kordianbruck** [comment]
Characters also now return valid data.
